version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./backend:/app/backend
    environment:
      - DATABASE_URL=sqlite:///backend/app/db/database.db
    ports:
      - "8002:8002"
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8003:8003"
    command: ["streamlit", "run", "frontend/🚀_Home.py", "--server.port=8003", "--server.address=0.0.0.0"]